# Este arquivo define a infraestrutura como código para o seu serviço no Render.
# Você pode fazer o deploy diretamente a partir dele.
# Coloque este arquivo na raiz do seu projeto (na pasta `backend`).

services:
  - type: web
    name: notas-internas-backend
    runtime: node
    plan: free # Ou o plano de sua preferência
    repo: https://github.com/Barreto0620/Note_HEMC.git # <-- IMPORTANTE: Troque pelo URL do seu repositório Git
    branch: main # Ou o nome da sua branch principal (ex: master)
    
    # Comandos para construir e iniciar sua aplicação
    buildCommand: "npm install && npm run build"
    startCommand: "node dist/server.js"

    # Configuração da rota de Health Check
    healthCheckPath: /api/health

    # Variáveis de Ambiente (configure os valores no dashboard do Render)
    envVars:
      - key: NODE_ENV
        value: production # Conforme seu .env
      - key: MONGO_URI
        # O valor será pego do seu Secret Manager ou inserido diretamente no dashboard
        # Ex: mongodb+srv://mariocovasdb:TUXL3dgwFvM94IsK@cluster0.ns4bwt1.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
        value: mongodb+srv://mariocovasdb:TUXL3dgwFvM94IsK@cluster0.ns4bwt1.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
        # Removido 'fromDatabase' pois você já tem a URI completa no .env
      - key: JWT_SECRET
        value: "@Mariocovas2025" # Conforme seu .env. Considere usar 'generateValue: true' para maior segurança em produção.
