# Este arquivo define a infraestrutura como código para o seu serviço de backend no Render.

services:
  - type: web
    name: notas-internas-backend
    runtime: node
    plan: free # Ou o plano de sua preferência
    repo: https://github.com/Barreto0620/Note_HEMC.git
    branch: main
    
    # MUITO IMPORTANTE: Define o diretório raiz para este serviço.
    # Isso fará com que 'buildCommand' e 'startCommand' sejam executados
    # A PARTIR DA PASTA 'backend/' dentro do seu repositório.
    rootDir: backend 

    # Comandos para construir e iniciar sua aplicação
    # O comando COMPLETO: primeiro instala dependências, DEPOIS executa o build do TypeScript.
    buildCommand: "npm install && npm run build" 
    # Inicia o servidor a partir do código transpilado na pasta 'backend/dist'.
    startCommand: "node dist/server.js"

    # Configuração da rota de Health Check
    healthCheckPath: /api/health

    # Variáveis de Ambiente (configure os valores no dashboard do Render)
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        value: "mongodb+srv://mariocovasdb:TUXL3dgwFvM94IsK@cluster0.ns4bwt1.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
      - key: JWT_SECRET
        value: "@Mariocovas2025" 
