# Este arquivo define a infraestrutura como código para o seu serviço de backend no Render.

services:
  - type: web
    name: notas-internas-backend
    runtime: node
    plan: free # Ou o plano de sua preferência
    repo: https://github.com/Barreto0620/Note_HEMC.git
    branch: main
    
    # Comandos para construir e iniciar sua aplicação
    # 'npm install' instala as dependências
    # 'npm run build' executa 'tsc' conforme seu package.json, gerando a pasta 'dist'
    buildCommand: "npm install && npm run build" 
    # 'node dist/server.js' inicia o servidor a partir do código transpilado
    startCommand: "node dist/server.js"

    # Configuração da rota de Health Check
    healthCheckPath: /api/health

    # Variáveis de Ambiente (configure os valores no dashboard do Render)
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        # O valor é fornecido diretamente, mas para produção, considere configurá-lo
        # no dashboard do Render como uma variável de ambiente secreta para maior segurança.
        value: "mongodb+srv://mariocovasdb:TUXL3dgwFvM94IsK@cluster0.ns4bwt1.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
      - key: JWT_SECRET
        # O valor foi colocado entre aspas para evitar erros de sintaxe YAML.
        # Para produção, 'generateValue: true' ou configurar como secreta no dashboard é mais seguro.
        value: "@Mariocovas2025" 
